
LSW = data.table(B_LSW_ID = 5, 
                 B_SOM_LOI = 8.65,
                 B_CLAY_MI = 15.8,
                 B_SAND_MI = 60.5,
                 B_SILT_MI = 23.71,
                 B_N_RT = 3834,
                 B_P_AL = 49,
                 B_P_CC = 2.71,
                 B_P_WA = 40,
                 B_P_SG = 22, 
                 B_FE_OX = 83,
                 B_AL_OX = 40,
                 B_RO_R = 0.5,
                 B_SA_W = 0.47,
                 B_SOM_LOI_SD = 6.67,
                 B_CLAY_MI_SD = 13.45,
                 B_SAND_MI_SD = 23.5,
                 B_SILT_MI_SD = 11.7,
                 B_N_RT_SD = 2928,
                 B_P_AL_SD = 13.5,
                 B_P_CC_SD = 1.51,
                 B_P_WA_SD = 15.6,
                 B_P_SG_SD = 14, 
                 B_FE_OX_SD = 59,
                 B_AL_OX_SD = 19,
                 B_RO_R_SD = 0.3,
                 B_SA_W_SD = 0.33)
                
test <- bbwp_field_properties(B_SOILTYPE_AGR = c('dekzand', 'loess'),
                              B_LU_BBWP = c('gras_permanent','rooivrucht'),
                              B_GWL_CLASS = c('III', 'VIII'),
                              B_SC_WENR = c(4, 2), 
                              B_HELP_WENR = c('AZW1AwF', 'AZW1AwF'),
                              B_AER_CBS = c('LG05','LG14'),
                              B_SLOPE_DEGREE = c(1.5,0.8),
                              A_CLAY_MI = c(15, 5),
                              A_SAND_MI = c(45, 65),
                              A_SILT_MI = c(40, 30),
                              A_SOM_LOI = c(5, 15), 
                              A_N_RT = c(4200, 1000),
                              A_FE_OX = c(500, 500), 
                              A_AL_OX = c(150, 150), 
                              A_P_CC = c(5, 1), 
                              A_P_AL = c(65, 5),
                              A_P_WA = c(52, 5), 
                              A_P_SG = c(38, 78),
                              D_SA_W = c(0.5, 1), 
                              D_RO_R = c(0.5, 0),
                              B_LSW_ID = 5,
                              LSW = LSW,
                              B_LU_BRP = c(265, 2014),
                              M_DRAIN = c(FALSE, FALSE),
                              M_GREEN = c(FALSE, TRUE)
                            )

test_that("check bbwp_field_properties", {
  expect_equal(
   object = test,
    expected = data.table(
      ngw_scr = c(0.4, 0.8),
      ngw_lea = c(0.2649, 0.487),
      ngw_nlv = c(0.55,0.16),
      nsw_scr = c(0.6, 0.2),
      nsw_gwt = c(0.9, 0.4),
      nsw_ro = c(0.5, 0.048),
      nsw_slope = c(0.75,0.4),
      nsw_ws = c(0.5, 1.0),
      nsw_nlv = c(0.0497, 0.1665),
      psw_scr = c(0.6, 0.2),
      psw_gwt = c(0.9, 0.4),
      psw_ro = c(0.5, 0.048),
      psw_slope = c(0.75,0.4),
      psw_ws = c(0.5, 1.0),
      psw_pcc = c(0.94, 0.13),
      psw_psg = c(0.87, 0.999),
      psw_pret = c(0, 0),
      npe_wri = c(0.055, 0.25),
      npe_pbi = c(0.97577, 0.02158),
      npe_wdri = c(0, 0.23),
      npe_nlv = c(0.95, 0.83),
      wue_wwri = c(0.055, 0.03),
      wue_wdri = c(0, 0.23),
      wue_whc = c(0.2338, 0.055),
      wue_gwr  = c(0.749, 0.153)
    ),
    tolerance = 0.01)
})

